Feature/JC19-271-film-details-related-data
saritasa-nest/camp-js-2022-maxim-korkin pull request #4
Opened 2022-02-09 16:03 UTC by maxineo

2022-02-10 03:33 UTC, thanhnguyen-saritasa commented on vanilla/src/features/filmDetails/renderListOfPlanets.ts
> +  listOfPlanets.forEach((planet, index) => {
What will happen if 'listOfPlanets' is 'null' or not 'Array'?

2022-02-10 03:34 UTC, thanhnguyen-saritasa commented on vanilla/src/features/filmDetails/renderListOfCharacters.ts
> +  listOfCharacters.forEach((character, index) => {
What will happen if 'listOfCharacters' is 'null' or not 'Array'?

2022-02-10 06:24 UTC, maxineo commented on vanilla/src/features/filmDetails/renderListOfPlanets.ts
> +  listOfPlanets.forEach((planet, index) => {
Well, fetch method always returns an array even if no planets with given ids were found. But I added exception handling in case something goes wrong with the request.

2022-02-10 06:24 UTC, maxineo commented on vanilla/src/features/filmDetails/renderListOfCharacters.ts
> +  listOfCharacters.forEach((character, index) => {
Same as planets.

2022-02-10 07:29 UTC, panov-aleksey-saritasa approved these changes

2022-02-10 07:52 UTC, timofei-maximov-saritasa commented on vanilla/src/services/planets/PlanetsService.ts
> +  }
Well, it seems that you have simillar method without any significant differences. What if you would need more enitites to fetch(like vehicles and species)? You will have a lot of duplicated code. Perhaps, we can move out this into separate method/function. I think generics will work there.

2022-02-10 08:07 UTC, panov-aleksey-saritasa commented on vanilla/src/services/firebase/FirebaseService.ts
> +  }
To not write the same map function for every entity you can implement it like this:
```ts
  public static mapQuerySnapshotToArray<TData, TDto>(snapshot: QuerySnapshot<TDto>, mapper: (dto: TDto) => TData): TData[] {
    return snapshot.docs.map(dto => mapper(dto.data()));
  }
```

2022-02-10 10:59 UTC, thanhnguyen-saritasa commented on vanilla/src/services/characters/CharactersService.ts
> +
How could you use blank line more useful?

2022-02-10 11:16 UTC, maxineo commented on vanilla/src/services/characters/CharactersService.ts
> +
I dont understand what you mean by using blank line. I could just remove it here.

2022-02-11 10:43 UTC, dbitkovski requested changes

2022-02-11 10:43 UTC, dbitkovski commented on vanilla/src/features/filmDetails/renderListOfCharacters.ts
> +export const renderListOfCharacters = async(characterIds: readonly number[]): Promise<void> => {
I'd say if a function renders something, it shouldn't fetch anything under the hood.
Try to follow [Single responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle). If you say your function renders a list, it should require the list and only render it

2022-02-11 11:25 UTC, golovachev-yaroslav approved these changes

2022-02-11 11:25 UTC, golovachev-yaroslav commented on vanilla/src/mappers/CharacterMapper.ts
> +import { Character } from '../interfaces/characters/character/Character';
`'../interfaces/characters/character/Character';` - It looks strange to many characters in the path, maybe needs to call another?

2022-02-11 11:30 UTC, maxineo commented on vanilla/src/mappers/CharacterMapper.ts
> +import { Character } from '../interfaces/characters/character/Character';
Well, folder "characters" contains  all interfaces related to character: Character itself and Dtos. And they are in separated folders too. That is why there is "characters/character".

2022-02-13 07:47 UTC, maxineo commented on vanilla/src/mappers/CharacterMapper.ts
> +import { CharacterFieldsDto } from './../interfaces/characters/DTO/CharacterFieldsDto';
I guess the problem is auto imports. Perhaps when I move the file to another folder it updates the path with `./`. But anyway I'll fix this.

2022-02-13 08:07 UTC, merged