Feature/js19 280 search
saritasa-nest/camp-js-2022-maxim-korkin pull request #6
Opened 2022-02-10 05:47 UTC by karbik-creator

2022-02-10 06:47 UTC, panov-aleksey-saritasa commented on vanilla/src/features/films/displayFilmsTable.ts
> +  return async(mode = PaginationModes.Init, newOrderingField: OrderingFields | null = null, valueSearch: string): Promise<void> => {
Please consider combining params for fetching into single object, it's a good practice since amount of fetch options can be a lot more than three and putting them into function as params and besides in right order could be inconvenient

2022-02-10 06:47 UTC, panov-aleksey-saritasa commented on vanilla/src/features/films/displayFilmsTable.ts
> +        onLastPage = await isLastPage(lastFilm, orderingField, orderingMode, valueSearch);
Same thing with combining fetch params. To not duplicate interfaces you can create base interface and [extend](https://www.typescriptlang.org/docs/handbook/interfaces.html#extending-interfaces) it for more specific cases.

2022-02-10 06:47 UTC, panov-aleksey-saritasa commented on vanilla/src/index.html
> +      <button type="button" class="search-btn"></button>
Since it's button without text, please, consider adding [title](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) attribute for semantics

2022-02-10 06:57 UTC, golovachev-yaroslav approved these changes

2022-02-10 06:57 UTC, golovachev-yaroslav commented on vanilla/src/index.css
> +  background-color: transparent;
You can reduce `background: url("./imgs/icon-search-32px.png") transparent center no-repeat;`

2022-02-13 10:25 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-02-14 06:54 UTC, elena-dragunova approved these changes

2022-02-14 12:39 UTC, maxineo commented on vanilla/src/features/films/displayFilmsTable.ts
> +  let newValueSearch: undefined | string;
I guess it is better to use `null` or just empty string instead of `undefined`.

2022-02-14 12:39 UTC, maxineo commented on vanilla/src/features/films/displayFilmsTable.ts
> +    if (options.valueSearch !== undefined) {
If `options.valueSearch` is `''` then `newValueSearch` will be reassigned to `''` and then reassigned again to `undefined` which seems strange.

2022-02-14 12:46 UTC, maxineo commented on vanilla/src/interfaces/options/FetchOptionsPagination.ts
> +  /** Urrent ordering mode.*/
Typo

2022-02-14 14:40 UTC, timofei-maximov-saritasa commented on vanilla/src/features/films/displayFilmsTable.ts
> +  return async(options: FetchOptionsFilterSort = DEFAULT_OPTIONS): Promise<void> => {
Please, specify return type of your `displayFilmsTable`. `Function` is not safe. 
You can do something like this:
```ts
type DisplayFunction = (options?: FetchOptionsFilterSort) => void;

export const displayFilmsTable = (): DisplayFunction => {
```

2022-02-14 14:40 UTC, timofei-maximov-saritasa commented on vanilla/src/features/films/addHeaderPagination.ts
>  export const addHeaderPagination = (header: Element | null, orderingField: OrderingFields, displayFunction: Function): void => {
And here we will have `DisplayFunction` type for our callback, which will provide typechecking for our function argument.

2022-02-15 08:57 UTC, golovachev-yaroslav requested changes

2022-02-16 08:17 UTC, golovachev-yaroslav approved these changes

2022-02-18 04:02 UTC, timofei-maximov-saritasa commented on vanilla/src/services/films/FilmsService.ts
> +      where(OrderingFields.Title, '<=', `${valueSearch}~`),
Please move `~` to a constant.

2022-02-20 05:04 UTC, pavel-romanov8 requested changes

2022-02-20 05:04 UTC, pavel-romanov8 commented on vanilla/src/services/films/FilmsService.ts
> +   * @param options - Field to order the results. Default value is 'pk'. Indicates if order should be ascending or descending.
We shouldn't describe every options field in the docs for the function. For that purpose we have interface docs, where we describing such things

2022-02-22 08:27 UTC, pavel-romanov8 commented on vanilla/src/features/films/displayFilmsTable.ts
> +    orderingMode: OrderingModes, newValueSearch: string | null): Promise<PageParameters> {
For functions with many arguments it is better to place each of them on a separate line:

```suggestion
  public static async getPageParameters(
  	films: readonly Film[],
  	orderingField: OrderingFields,
    orderingMode: OrderingModes,
    newValueSearch: string | null
  ): Promise<PageParameters> {
```

2022-02-22 08:27 UTC, pavel-romanov8 commented on vanilla/src/interfaces/options/PageParameters.ts
> +  readonly lastFilm: Film | null;
Please, provide documentation for each interface field

2022-02-22 08:27 UTC, pavel-romanov8 commented on vanilla/src/interfaces/options/PageParameters.ts
> + * The first and last films on the page and whether the given page is the first or last.
As is stated in previous comments there we shouldn't describe each field here. This place is meant to describe the interface as a standalone entity or an object. F.e. you write here something like this:
```
Configuration of the current page.
```

2022-02-22 08:27 UTC, pavel-romanov8 commented on vanilla/src/interfaces/options/PaginationOptions.ts
> +export interface PaginationOptions extends FilterSortOptions {
The same as for `PageParameters`

2022-02-22 08:27 UTC, pavel-romanov8 commented on vanilla/src/interfaces/options/PaginationOptions.ts
> +/* eslint-disable jsdoc/require-jsdoc */
Why did you disable eslint?

2022-02-22 08:27 UTC, pavel-romanov8 commented on vanilla/src/interfaces/options/QueryConstraintParameters.ts
> +export type QueryConstraintParameters = Pick<PaginationOptions, 'valueSearch' | 'orderingMode' | 'orderingField' >;
Please, leave some description for types like this

2022-02-22 08:27 UTC, pavel-romanov8 commented on vanilla/src/services/films/FilmsService.ts
> + readonly QueryConstraint[] {
Please, don't make a function output read-only. Why should function care about what its clients will do with the output?

2022-02-22 08:27 UTC, pavel-romanov8 commented on vanilla/src/services/films/FilmsService.ts
> +
Please, remove empty line

2022-02-28 10:20 UTC, pavel-romanov8 approved these changes

2022-02-28 10:20 UTC, pavel-romanov8 commented on vanilla/src/interfaces/options/PageParameters.ts
> +  /** * Last film on the page or null if the page is empty.*/
Please, remove third `*` sign in docstring

2022-02-28 10:26 UTC, merged