Feature/jc19 271 film creation edition
saritasa-nest/camp-js-2022-maxim-korkin pull request #7
Opened 2022-02-17 10:12 UTC by maxineo

2022-02-17 10:20 UTC, golovachev-yaroslav approved these changes

2022-02-17 10:54 UTC, maxineo commented on vanilla/src/films/film/index.html
> +    <a class="edit-link btn">Edit</a>
This is not a button, this is a link styled as button(`btn` is a library class), its `href` is added dynamycally in ts to contain primary key of the current film.

2022-02-17 12:04 UTC, elena-dragunova approved these changes

2022-02-17 16:10 UTC, timofei-maximov-saritasa commented on vanilla/src/features/filmForm/fillFormValues.ts
> +  const dateString = `${year}-${month}-${day}`;
Perhaps, we should move it separate function?

2022-02-17 17:10 UTC, panov-aleksey-saritasa requested changes

2022-02-17 17:10 UTC, panov-aleksey-saritasa commented on vanilla/src/features/filmForm/removeProducerInput.ts
> +    }
Again about magic numbers, try to think from the code reader's point of view. It's not clear why some method should be called when some variable equals exactly to `2`

2022-02-18 05:34 UTC, viktor-sakhno-saritasa commented on vanilla/src/interfaces/films/DTO/EditableFilmFieldsDto.ts
> +  readonly 'fields.title': string;
It is not clear, why do you use string literal for interface property. Please, give a more detailed description. Also, I think you can create `fields` property and describe the interface for it.

2022-02-18 09:52 UTC, golovachev-yaroslav approved these changes

2022-02-18 09:57 UTC, maxineo commented on vanilla/src/interfaces/films/DTO/EditableFilmFieldsDto.ts
> +  readonly 'fields.title': string;
Fields of film are contained in fields map in firestore and Im not updating all of them, so I have to use `fields.property` for updating. If I just use fields interface for this purpose, then it will override entire `fields` in the document and all properties which are not used in my domain model will be lost.

2022-02-18 10:00 UTC, maxineo commented on vanilla/src/interfaces/films/DTO/EditableFilmFieldsDto.ts
> +  readonly 'fields.title': string;
And I provided additional description to clarify this.

2022-02-19 13:36 UTC, chernodub requested changes

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/features/filmForm/initFilmForm.ts
> +  addProducerButton?.addEventListener('click', addProducerInput);
I recommend [asserting](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions) for non-null in such cases, in order to make your code easier to debug, in case someone decides to remove/change the `add-producer-button` identifier (you could create a util function for this or use, or use some existing tooling, like [this](https://github.com/elierotenberg/typed-assert))

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/features/filmForm/switchRemoveProducerButton.ts
> +export const switchRemoveProducerButton = (): void => {
Usually, we prefer the term `toggle` when switching between binary options, also you should specify in the name that this function toggles the disabled state, in order to be more explicit

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/films/create/index.css
> +.producers-btns-container {
[Please avoid contractions](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#avoid-contractions)

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/films/create/index.css
> +.header {
As far as I understand this header is related to a form-creation page only, right? If so, I think you should slightly revise your BEM structure and make your names more specific

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/films/create/index.ts
> +await initFilmForm(form);
Cool, top-level await 🙂 
But, in future, remember that [it doesn't work for Safari 14.8](https://caniuse.com/?search=top%20level%20await), and our company usually supports N-2 versions of the browser

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/films/create/index.ts
> +  const highestPrimaryKey = await FilmsService.getMaximumPrimaryKey();
I believe this logic should be handled within a service internally, your components should not know anything about the serialization/implementation/whatever of your domain models. So, what I mean is that your service should only accept a data for film creation, without the id, and then, create it internally, right in the `addFilm` method

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/films/edit/index.css
> +}
Seems that this stuff is duplicated, try working some shared-like approach for your styles of edit/create pages

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/films/edit/index.ts
> +    format: 'dd.mm.yyyy',
I see the format is used several times in your app, I recommend creating a global const for this, in order to preserve things consistent by having a single source of truth

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/films/edit/index.ts
> +if (!isNaN(primaryKey) && primaryKey !== 0) {
Why `primaryKey !== 0`, this is some implicit logic you're meaning here.
1. Are you sure it's the responsibility of a component to handle this?
2. It's a good practice to leave comments when using workarounds like that so that other devs could understand what you meant by this code :)

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/films/edit/index.ts
> +  document.location = '/';
Probably, a user should be notified somehow that a film is non-existent

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/films/film/index.ts
> +    if (!isNaN(primaryKey) && primaryKey !== 0) {
This stuff is duplicated in films/edit/index.ts, please try reusing your code :)

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/interfaces/BaseEntity.ts
> +  /** Creation date of the entity in the DB. */
Your domain modes should never know about the DB and any serialization information, you should operate with business language only on this layer

2022-02-19 13:36 UTC, chernodub commented on vanilla/src/interfaces/films/DTO/EditableFilmFieldsDto.ts
> +  readonly 'fields.title': string;
That is some smart hack 😆

2022-02-24 03:55 UTC, golovachev-yaroslav approved these changes

2022-02-25 16:47 UTC, maxineo commented on vanilla/src/features/filmForm/createFilmForm.ts
> +      <label for="title-input">Title</label>
Ye, but sadly the styling library Im using doesnt work with such labels properly, and I have no idea why.

2022-02-25 17:27 UTC, maxineo commented on vanilla/src/features/filmForm/initFilmForm.ts
> +export const initFilmForm = async(form: HTMLFormElement): Promise<void> => {
I dont know, its probably just a habit. But I think you are right that its better to use function declaration when I am declaring a global function.

2022-02-25 18:51 UTC, maxineo commented on vanilla/src/films/edit/index.ts
> +    format: 'dd.mm.yyyy',
This `option` object is supposed to be used by styling library I mentioned in the label conversation and actually it doesnt work(again I have no idea why, docs is pretty limited) so I just removed it. Anyway default format is `dd.mm.yyy`.

2022-03-16 05:38 UTC, chernodub approved these changes

2022-03-16 07:09 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-03-16 08:03 UTC, merged