Feature/JC19-286 angular init auth
saritasa-nest/camp-js-2022-maxim-korkin pull request #8
Opened 2022-02-24 02:45 UTC by maxineo

2022-02-24 03:04 UTC, timofei-maximov-saritasa requested changes

2022-02-24 03:04 UTC, timofei-maximov-saritasa commented on angular/src/app/features/register/register.module.ts
> +    MatButtonModule,
It is better to create `MaterialModule` for `material` components, then you need to import this module into shared module.

2022-02-24 03:04 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.ts
> +  public constructor(public readonly authService: AuthService) { }
Do you want to make your `authService` public?

2022-02-24 03:04 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.ts
> +  private destroy$ = new Subject<void>();
[Do not forget to add readonly](https://frontendwiki.saritasa.rocks/pages/development/languages/typescript.html#promote-immutability)

2022-02-24 05:57 UTC, timofei-maximov-saritasa commented on angular/src/app/features/auth/register-form/register-form.component.ts
> +    this.registerError$.complete();
There is no need for this. You subscribe to this subject in your `html` template via `async` pipe. Angular will manage subscription for you.

2022-02-24 05:57 UTC, timofei-maximov-saritasa commented on angular/src/app/app-routing.module.ts
> +  { path: 'register', component: RegisterFormComponent, canActivate: [NonAuthGuard] },
This should be part of auth routing module

2022-02-24 05:57 UTC, timofei-maximov-saritasa commented on angular/src/app/features/auth/login-form/login-form.component.ts
> +  private destroy$ = new Subject<void>();
Please, add `readonly`

2022-02-24 05:57 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/material.module.ts
> +    MatToolbarModule,
You can declare array with material modules and reuse it

2022-02-24 05:57 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.html
> +      <span (click)="signOut()"> Logout </span>
I think, it should be button

2022-02-24 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/components/auth-form/auth-form.component.ts
> +  public readonly passwordControl = new FormControl('', [Validators.required, Validators.pattern(/\S+/)]);
FYI, you can use `FormBuilder`

2022-02-24 06:56 UTC, timofei-maximov-saritasa commented on angular/src/app/shared/material.module.ts
> +const materialModules = [
Please, rename it to `MATERIAL_MODULES`

2022-02-24 07:55 UTC, timofei-maximov-saritasa approved these changes

2022-02-24 12:53 UTC, panov-aleksey-saritasa requested changes

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/.prettierrc.json
> +{}
If this file is empty I think you can omit it

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/core/guards/non-auth.guard.ts
> + * Guard which allows links for unauthenticated users only.
~links~ -> 'navigation to the route'

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/auth.service.ts
> +  public isSignedIn$: Observable<boolean>;
Missing `readonly` modifier

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/auth.service.ts
> +  public isSignedIn$: Observable<boolean>;
Please, put class fields above `constuctor`

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/auth-form/auth-form.component.ts
> +
Prefer using [FormBuilder](https://angular.io/api/forms/FormBuilder#description) to work with forms

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/auth-form/auth-form.component.ts
> +  public readonly emailControl = new FormControl('', [Validators.required, Validators.pattern(/^[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z]+$/)]);
You can use `Validators.email` for this :)

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/auth-routing.module.ts
> +  declarations: [],
Please, remove `declarations` property if it's empty

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/login-form/login-form.component.html
> +  [formHeader]="'Login'"
Since it's a simple static string, you don't need property binding here

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/login-form/login-form.component.ts
> +        },
FYI, be careful with `complete` callback and `takeUntil`, since it's possible that `complete` callback would be executed on component destruction (for example, when navigation is happening but source stream is still running)

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/login-form/login-form.component.ts
> +
Again, please, keep your class properties at the top. This way you make your class far more readable, since you don't have to search for its fields somewhere inside.

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/auth/register-form/register-form.component.html
> +  [formHeader]="'Register'"
Again about property binding with static string

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.html
> +  </span>
I think `<span>` tags are extra here

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.css
> +
Are you sure it's good idea to set global variable in component? I don't think a component is responsible for this. You should do something like this in css theme config of your app.

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.html
> +    <span class="navbar__spacer"></span>
Please, avoid spacers in your layout. You can easily achieve the same result with flexbox/grid, but it will be clearer and easier to maintain.

2022-02-24 12:53 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.html
> +    <a routerLink="/" class="navbar__link"><div>SW Films</div></a>
`div` is extra here, isn't it?

2022-02-24 13:19 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/auth.service.ts
> +      mapTo(null),
If value emitted by stream doesn't matter, prefer `mapTo(void 0)` or `ignoreElements` instead

2022-02-24 13:19 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/auth.service.ts
> +  public signIn(email: string, password: string): Observable<null | Error> {
Actually, you shoudn't force a consumer of your service to deal with errors directly. They can handle it if they need to

2022-02-24 16:18 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/auth/auth-form/auth-form.component.html
> +    [disabled]="emailControl.invalid || passwordControl.invalid"
If you will use the form builder as Alexey suggested, you can use `[disabled]="!form.valid"` instead.

2022-02-24 16:18 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.html
> +  </span>
Same with `<div>Login</div>`

2022-02-24 16:18 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.ts
> +    this.isSignedIn$ = this.authService.isSignedIn$;
I think that you can initialize the `isSignedIn$` property right on the declaration, instead of specifying it in the constructor.
`public readonly isSignedIn$: Observable<boolean> = this.authService.isSignedIn$;`
or without type definition
`public readonly isSignedIn$ = this.authService.isSignedIn$;`

2022-02-24 16:18 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.ts
> +  }
Nice leak tracking job! )

2022-02-25 01:18 UTC, dbitkovski commented on angular/src/app/core/services/auth.service.ts
> +  public signIn(email: string, password: string): Observable<null | Error> {
Aleksey is right. Unfortunately, we don't have such a tool to point that `signIn` throws an error. So if you want to notify method clients that error should be handled you might use `@throw` tag in jsdoc.

2022-02-25 01:18 UTC, dbitkovski commented on angular/src/app/features/auth/auth-form/auth-form.component.ts
> +
I think Alexey meant to use `FormGroup` and put your controls there. And to make it more convenient to work you can use `FormBuilder`

2022-02-25 01:18 UTC, dbitkovski commented on angular/src/app/features/auth/login-form/login-form.component.ts
> +import { AuthInfo } from './../../../core/models/AuthInfo';
Format your imports to have the same path (both of imports work with `core` folder but looks different)

2022-02-25 03:01 UTC, maxineo commented on angular/src/app/features/auth/auth-form/auth-form.component.ts
> +  public readonly emailControl = new FormControl('', [Validators.required, Validators.pattern(/^[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z]+$/)]);
It works strange to me allowing emails like `test@test`, so i used regexp to make sure email domains always contain `.something`

2022-02-25 03:10 UTC, kristinaSvobodinaSaritasa commented on angular/src/app/features/auth/auth-form/auth-form.component.ts
> +  public readonly emailControl = new FormControl('', [Validators.required, Validators.pattern(/^[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z]+$/)]);
In this case, it is better to wrote your custom validator in separate file to reuse it.

2022-03-03 08:29 UTC, pavel-romanov8 requested changes

2022-03-03 08:29 UTC, pavel-romanov8 commented on angular/src/app/core/models/AuthInfo.ts
> + * Interface with the fields required for authentication.
There is no need to mention that it is an interface, I guess it is already clear. Try to describe models from the perspective of business logic instead of its implementation

2022-03-03 08:29 UTC, pavel-romanov8 commented on angular/src/app/core/services/auth.service.ts
> +        return throwError(() => new Error('Incorrect email of password'));
You can shorten it to:
```suggestion
      case FirebaseAuthErrors.WrongEmail:
      case FirebaseAuthErrors.WrongPassword:
        return throwError(() => new Error('Incorrect email of password'));
```

2022-03-03 08:29 UTC, pavel-romanov8 commented on angular/src/app/features/auth/auth-form/auth-form.component.ts
> +  public authForm = this.formBuilder.group({
Since you are not mutating it anywhere it can be a read-only field

2022-03-03 08:29 UTC, pavel-romanov8 commented on angular/src/app/shared/directives/email-validator.directive.ts
> +  return (control: AbstractControl): ValidationErrors | null => {
I'm not sure that it is a good idea to invent the wheel here. Built-in Angular `Validators` class already have a validator for email

2022-03-03 08:29 UTC, pavel-romanov8 commented on angular/src/app/features/auth/register-form/register-form.component.ts
> +export class RegisterFormComponent implements OnDestroy {
The `LoginFormComponent` basically looks the same as this one. Please, generalize logic to remove repeated parts

2022-03-03 17:44 UTC, maxineo commented on angular/src/app/shared/directives/email-validator.directive.ts
> +  return (control: AbstractControl): ValidationErrors | null => {
I described above why I decided to use regexp for this. Besides that why not to prictice with some non build-in things :)
[https://github.com/saritasa-nest/camp-js-2022-maxim-korkin/pull/8#discussion_r814439915](url)

2022-03-04 01:00 UTC, pavel-romanov8 commented on angular/src/app/shared/directives/email-validator.directive.ts
> +  return (control: AbstractControl): ValidationErrors | null => {
@maxineo For such cases always leave comment abot the reason in the code, so there will less questions.

I still don't see a reason to use the custom logic because the Angulra email validator following the [WHATWG spec](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address). That means that it is the how it meant to work. And we, as a developers, should follow the spec and do not invent the whell.

2022-03-04 09:04 UTC, elena-dragunova approved these changes

2022-03-10 06:38 UTC, pavel-romanov8 approved these changes

2022-03-10 06:38 UTC, pavel-romanov8 commented on angular/src/app/features/auth/login-form/login-form.component.html
> +    <p>{{ error$ | async }}</p>
You can use the `ngIf` on `p` tag directly:
```ts
<p *ngIf="error$ | async as error>{{ error }}</p>
```

2022-03-10 06:38 UTC, pavel-romanov8 commented on angular/src/app/features/auth/auth-form/auth-form.component.ts
> +  protected readonly subscriber = {
It is not a subscriber, but an observer and please, add type declaration for the field

2022-03-10 07:16 UTC, merged