Feature/JC19-286 angular films table and film details page
saritasa-nest/camp-js-2022-maxim-korkin pull request #9
Opened 2022-03-10 14:29 UTC by maxineo

2022-03-14 06:25 UTC, panov-aleksey-saritasa requested changes

2022-03-14 06:25 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-table/films-table.component.ts
> +  ];
Why not combine it all into one array?)

2022-03-14 06:25 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-table/films-table.component.ts
> +  }
You can combine this streams with [merge](https://www.learnrxjs.io/learn-rxjs/operators/combination/merge)

2022-03-14 06:25 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-table/films-table.component.ts
> +    auditTime(300),
Why do you use `auditTime` here instead of `debounceTime`?

2022-03-14 06:25 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-table/films-table.component.ts
> +    ).subscribe(this.searchingValue$);
It's not clear what's happening here

2022-03-14 06:25 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-table/films-table.component.ts
> +  public readonly films$ = combineLatest(
To make your class more readable you can move out stream creation into `private` method `initFilmsStream(): Observable<readonly Film[]>` and then initialize `films$` with it

2022-03-14 08:28 UTC, maxineo commented on angular/src/app/core/utils/enums/PaginationModes.ts
> +export enum PaginationModes {
I agree, renamed it.

2022-03-14 08:57 UTC, maxineo commented on angular/src/app/features/films/films-table/films-table.component.html
> +  [isLastPage]="!!(isLastPage$ | async)"
Im casting it to boolean since async pipe can return null.
[https://stackoverflow.com/questions/61780339/angular-ivy-stricttemplates-true-type-boolean-null-is-not-assignable-to-type](url)

2022-03-14 09:24 UTC, maxineo commented on angular/src/app/features/films/films-table/films-table.component.ts
> +  ];
Im using these fields later in `mapHeaderToSortingField()` and `mapSortingFieldToHeader()` methods to map them to `FilmSortingField` enum which are actual values to sort by. And these fields are provided as array to mat-table.

2022-03-14 09:35 UTC, maxineo commented on angular/src/app/features/films/films-table/films-table.component.ts
> +    auditTime(300),
I just looked into defference between them and `debouceTime` fits better here.

2022-03-14 12:05 UTC, timofei-maximov-saritasa commented on angular/src/app/features/films/pagination-buttons/pagination-buttons.component.ts
> +  }
Please, stick with [naming convention](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#ahclc-pattern) for methods

2022-03-14 12:06 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-table/films-table.component.html
> +  [isLastPage]="!!(isLastPage$ | async)"
Recommend rewriting it more explicitly then, like `(isFirstPage$ | async) === true`

2022-03-14 12:25 UTC, maxineo commented on angular/src/app/core/services/filmsService/getFilmsQueryConstraints.ts
> +    const veryBigSymbol = '\uf8ff';
Well, it should be

2022-03-16 06:58 UTC, elena-dragunova approved these changes

2022-03-16 06:59 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/filmsService/getFilmsQueryConstraints.ts
> +    const veryBigSymbol = '\uf8ff';
@maxineo According to [firebase docs](https://firebase.google.com/docs/database/rest/retrieve-data)
The \uf8ff character used in the query above is a very high code point in the Unicode range. Because it is after most regular characters in Unicode, the query matches all values that start with a b.

2022-03-16 07:10 UTC, chernodub requested changes

2022-03-16 07:10 UTC, chernodub commented on angular/src/app/features/films/films-table/films-table.component.ts
> +    this.router.navigateByUrl(`films/film/${film.pk}`, { state: film });
Could you use `routerLink` directive instead?

2022-03-16 07:38 UTC, maxineo commented on angular/src/app/core/services/filmsService/getFilmsQueryConstraints.ts
> +    const veryBigSymbol = '\uf8ff';
Renamed it

2022-03-16 13:09 UTC, maxineo commented on angular/src/app/core/services/filmsService/getFilmsQueryConstraints.ts
> +    queryConstraints.push(where(FilmSortingField.Title, '<=', `${titleSearchingValue}${veryBigSymbol}`));
The \uf8ff character used in the query is a very high code point in the Unicode range. Because it is after most regular characters in Unicode, the query matches all values that start with searching value.

2022-03-16 14:03 UTC, maxineo commented on angular/src/app/features/films/films-table/films-table.component.html
> +  </ng-container>
I could not find any examples how to use it with mat-sort especially considering im not adding ability to sort by producers.

2022-03-17 04:18 UTC, maxineo commented on angular/src/app/core/services/filmsService/getFilmsQueryConstraints.ts
> +    queryConstraints.push(limitToLast(countOfFilmsOnPage + 2));
I used `endBefore` constraint and it didn't work with `+1`, so I had to use `+2`, now I changed it to `endAt` and it works with `+1`, so fixed.

2022-03-18 08:56 UTC, dbitkovski approved these changes

2022-03-18 08:56 UTC, dbitkovski commented on angular/src/app/features/films/film-details/film-details.component.ts
> +    takeUntil(this.destroy$),
It's better to use `takeUntil` as the last operator to ensure unsubscription from any inner observables. Despite you don't have inner observables, stick to this practice to avoid mistakes in future.
Btw, we use eslint rules in our base template that now has a [rule](https://github.com/cartant/eslint-plugin-rxjs/blob/main/docs/rules/no-unsafe-takeuntil.md) for this :)

2022-03-18 08:56 UTC, dbitkovski commented on angular/src/app/features/films/searching-input/searching-input.component.ts
> +  private destroy$ = new Subject<void>();
make it `readonly` please :)

2022-03-19 04:57 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-03-25 02:35 UTC, pavel-romanov8 requested changes

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/films.service.ts
> +  private parseFilmsList(films: Film[], { paginationMode, countOfFilmsOnPage }: FilmsFetchOptions): Film[] {
You are not mutating films array in any way. Let's declare it as a read-only array, to keep the function contract more explicit.

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/films.service.ts
> +      return { hasNext: countOfFilms === countOfFilmsOnPage + 1, hasPrev: false };
I see that you are repeating this part `countOfFilms === countOfFilmsOnPage + 1` 3 times. Let's move it to a variable

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/films.service.ts
> +        return film.releaseDate.toISOString().slice(0, 10);
And that is some implicit thing that we should at least document. Why are you slicing it, and why only by 10?

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/films.service.ts
> +        throw new Error('Failed to recognize FilmSortingField.');
Usually, it is also a good thing to add the result that caused the error in the message itself:
```ts
throw new Error(`Failed to recognize ${sortingField}. There is no such values in FilmSorrtingField`);
```

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/films.service.ts
> +      map(films => this.filmMapper.fromDto(films[0])),
What is films will be an empty array?

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/films.service.ts
> +      first(),
I'm not sure why you need to use `first` here. As I see, you are only using it withing the film resolver. It would be better to place it there, instead of a service.

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/films.service.ts
> +        return FilmSortingFieldDto.Title;
That way, typescript won't complain if you add some new properties to `FilmSortingField`. Instead, prefer using static maps like: `Record<FilmSortingField, FilmSortingFieldDto>`

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/films.service.ts
> +         The \uf8ff character used in the query is a very high code point in the Unicode range.
Please, format the docs properly, like you did for the `sortingField` above

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/interfaces/films-fetch-options.ts
> + * Options used for fetching films by the FilmsService.
Please, don't describe the usage of the interface / entity in the docs for it. It is only meant to describe interface itself.

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/core/services/filmsService/interfaces/films-pagination.ts
> +  readonly films: Film[];
Can we keep the films array read-only as well?

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/features/films/film-details/film-details.component.html
> +  <p></p>
What is the purpose of the empty tag?

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/features/films/film-details/film-details.component.html
> +<div *ngIf="this.film$ | async as film">
There is no need to use `this` on a template

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/features/films/film-details/film-details.component.html
> +    <li *ngFor="let producer of film.producers; trackBy: trackProducer">
There is no need to use `tackBy` for primitives

2022-03-25 02:35 UTC, pavel-romanov8 commented on angular/src/app/features/films/film-details/film-details.component.ts
> +  public readonly film$: Observable<Film> = this.route.data.pipe(
Typescript can infer type by itself, there is no need to explicitly add it. Or maybe it is some implicit casing?)

2022-03-29 15:47 UTC, maxineo commented on angular/src/app/core/services/filmsService/getFilmsQueryConstraints.ts
> +    queryConstraints.push(limitToLast(countOfFilmsOnPage + 2));
Nevermind, `endAt` is definetly not what is needed here. After some experiments I concluded that  `limitToLast` with `endBefore` counts the last document we dont need and then `endBefore` constraint just removes it from the result so we are getting one less document than expected so i use +2 here instead of +1.
I may be wrong here since this is really strange behavior, but this is how it works in my application and this is the only reason I see.

2022-03-29 18:22 UTC, maxineo commented on angular/src/app/core/services/filmsService/enums/film-sorting-field.ts
> +  ReleaseDate = 'release_date',
Honestly I dont know, changed it to camel case.

2022-03-29 18:26 UTC, maxineo commented on angular/src/app/core/services/filmsService/films.service.ts
> +      return { hasNext: countOfFilms === countOfFilmsOnPage + 1, hasPrev: false };
2 times now.
https://github.com/saritasa-nest/camp-js-2022-maxim-korkin/pull/9#discussion_r837637296

2022-03-29 19:23 UTC, maxineo commented on angular/src/app/core/services/filmsService/films.service.ts
> +      map(films => this.filmMapper.fromDto(films[0])),
I handle this in resolver. But i added length checking of array as side effect so now it throws error if array is empty.

2022-03-29 19:55 UTC, maxineo commented on angular/src/app/features/films/film-details/film-details.component.ts
> +  public readonly film$: Observable<Film> = this.route.data.pipe(
I had to specify that the data received from the route is of type `Film`, otherwise it is goind to be `any`. I could also do it like this:

```

> public readonly film$: Observable<Film> = this.route.data.pipe(
>     map(data => data[FILM_DATA] as Film),
>     takeUntil(this.destroy$),
>   );
```

2022-03-31 05:48 UTC, chernodub approved these changes

2022-04-04 08:34 UTC, closed without merging